### ISSUE TITLE
Image Duplication on First Load

### ISSUE THREAD

**Issue by MaggieAppleton** [MaggieAppleton/maggieappleton.com#118]
When you navigate directly to a post from a link that contains many images (eg. https://maggieappleton.com/garden-history), some of the images are duplicated in places where they should not be.

It overrides the image URL declared in the MDX, and replaces it with a URL of another image from another part of the page.

This only occurs when you've never visited the site before, and you go directly to the post from a link. If you navigate to the post vias the homepage or /garden page, the issue doesn't occur.

Issue split off from #72

**Comment by MaggieAppleton** [comment]
Same issue is happening again on https://maggieappleton.com/nontechnical-gardening.

To recreate it, open the page in a private browse window and navigate directly to the page link. Last two images are duplicates of one of the further up ones. Navigating to home, and then back to the article page fixes it.

**Comment by texastoland** [comment]
Fixed by #122?

**Comment by MaggieAppleton** [comment]
Yup, fixed 👍
