### ISSUE TITLE
Text and Image Styles Rendering Incorrectly on First Load

### ISSUE THREAD

**Issue by MaggieAppleton** [MaggieAppleton/maggieappleton.com#119]
Some text styling is rendering incorrectly if you go to a page link directly for the first time, and you haven't visited the site before. To test this, open a link directly in a new private window (https://maggieappleton.com/garden-history)

To see the post load correctly, first navigate to http://maggieappleton.com/garden, then click on the post (A Brief History and Ethos of the Digital Garden).

This happens across multiple posts on the site, but this particular post has the most visible cases.

---

For example, here is a paragraph that's showing up with an incorrectly small font size and centred alignment:

![image](https://user-images.githubusercontent.com/5599295/110238468-b024d780-7f39-11eb-8c94-93e96e1d51b5.png)

---

If you navigate away from the page back to the 'Digital Garden' main page, then click directly onto the same post (titled 'A Brief History & Ethos of the Digital Garden'), and scroll to the same section, the paragraph renders correctly:

![image](https://user-images.githubusercontent.com/5599295/110238475-bf0b8a00-7f39-11eb-803e-582c5e6535ac.png)

This issue is a split off from #72

**Comment by texastoland** [comment]
Fixed by #122?

**Comment by MaggieAppleton** [comment]
Yup, all fixed 👍
