### ISSUE TITLE
thoughts on the last post

### ISSUE THREAD

**Issue by genderev** [MaggieAppleton/maggieappleton.com#120]
[About this.](https://github.com/MaggieAppleton/maggieappleton.com/commit/3444c8d4500e26eec05b03d063164a80a4029a20#diff-1882866d8c311dd1dd04a82f486633c52b8635965e97d2857bb828f50a2db3dc)

Why are dark rooms and boxy hardware __at odds__ with pastel shades and baby animals? (Recreating the gender binary through code aesthetics - it has to be one or the other.)

Why is neon green _man_ and pastel is _femme_  (by which you mean "woman")? Why? The creator of bubblesort, the store you cited as _femme dev_ phenomena, even tweeted themself that [not all girls like pink things](https://nitter.himiko.cloud/partytimeHXLNT/status/1368997593250938881#m). So why did you define pink as equal to woman?

New draft:

- some programmers believe the beauty of the [system/code/hardware] is self-evident and shouldn't contaminated by decoration 
- other programmers have realized that this idea can lead to austere, unfriendly working environments
- "work" here can mean producing a body of work and/or producing capital
- cute computing is the process of adding warm colors to a programmer's workspace

**Comment by MaggieAppleton** [comment]
It's a seedling note with a collection of observations, not a complete argument. 

I think you might be reading things that aren't there?
Re: "why did you define pink as equal to woman?"
I don't think I did

There's a reason I used the word "femme," it means "having an appearance or other qualities of a type traditionally seen as feminine"
As in, historically, the aesthetics on display in the post are traditionally associated with the feminine. That's a well-document reality, not a personal argument or opinion. As a woman who personally doesn't like pink, I heartily agree with that tweet

It sounds like you should write your own post :)
