### ISSUE TITLE
Add Setup Instructions

### ISSUE THREAD

**Issue by paultegnazian** [MaggieAppleton/maggieappleton.com#90]
Hello, I like the format/design of your website so I git cloned the repo. I encountered a 404 error.

What I did:
1. git clone <repo paste>
2. yarn
3. yarn start
4. open browser and went to localhost indicated (localhost:5000)
5. <404 Error> 
<img width="361" alt="Screen Shot 2020-09-26 at 7 18 49 PM" src="https://user-images.githubusercontent.com/68792831/94351965-3228e000-002d-11eb-8405-1ef579f5bad3.png">

I am completely at a loss for why the 404 error occurred. Also the 404 error page isn't the 404.js version. Looks like the src files are not being read.

**Comment by MaggieAppleton** [comment]
Hey paul - I keep my site open source to let people poke around and learn from it, but it's not meant to be a website template to copy.

If you're just hoping to play around with a local version to understand how it works that's fine.

The issue you're having is that the site is built with gatsby, so you'll need to have the gatsby-cli installed and then run gatsby develop
